// Shared invoice builder -- used both by buildInvoiceTemplate.mjs (writes
// the example template into client-documents/templates/, with clearly
// bracketed placeholder data) and generate-invoice.mjs (the real, on-demand
// generator, called with real venue/line-item data). Same function, same
// visual output either way -- a "template" here means "an example render of
// this exact builder," not a separate hand-maintained file that could drift
// from what the generator actually produces.
import {
  makeDocument,
  clauseHeading,
  body,
  simpleTable,
  COLORS,
  FONTS,
  Paragraph,
  TextRun,
  BorderStyle,
  AlignmentType,
} from "./brandKit.mjs";

export function pendingField(fieldLabel) {
  return new Paragraph({
    spacing: { after: 60 },
    children: [
      new TextRun({ text: `${fieldLabel}: `, font: FONTS.mono, color: COLORS.clayBrown, size: 18 }),
      new TextRun({ text: "PENDING", font: FONTS.mono, bold: true, color: COLORS.preserveRed, size: 18 }),
    ],
  });
}

export function buildInvoiceSections({
  invoiceNumber,
  invoiceDate,
  dueDate,
  venueName,
  venueAddress,
  lineItems,
  isSampleTemplate = false,
}) {
  const total = lineItems.reduce((sum, li) => sum + li.amount, 0);
  const money = (n) => `$${n.toFixed(2)} AUD`;

  const sections = [];

  if (isSampleTemplate) {
    sections.push(
      new Paragraph({
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: COLORS.preserveRed, space: 6 } },
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: "SAMPLE TEMPLATE — NOT A REAL INVOICE. Generated by scripts/client-documents/generate-invoice.mjs for real use.",
            font: FONTS.mono,
            bold: true,
            color: COLORS.preserveRed,
            size: 16,
          }),
        ],
      }),
    );
  }

  sections.push(
    body(`Invoice ${invoiceNumber}`, { after: 40, bold: true }),
    body(`Invoice date: ${invoiceDate}     Due date: ${dueDate}`, { after: 260 }),
  );

  sections.push(clauseHeading("Bill to"));
  sections.push(body(venueName, { after: 40, bold: true }));
  if (venueAddress) sections.push(body(venueAddress, { after: 260 }));
  else sections.push(body(" ", { after: 260 }));

  sections.push(clauseHeading("Line items"));
  sections.push(
    simpleTable(
      ["Description", "Qty", "Rate", "Amount"],
      lineItems.map((li) => [li.description, String(li.qty), money(li.rate), money(li.amount)]),
      [5238, 900, 1600, 1900],
    ),
  );
  sections.push(
    new Paragraph({
      spacing: { before: 160, after: 260 },
      alignment: AlignmentType.RIGHT,
      children: [
        new TextRun({ text: "Total: ", font: FONTS.display, bold: true, color: COLORS.ink, size: 24 }),
        new TextRun({ text: money(total), font: FONTS.display, bold: true, color: COLORS.preserveRed, size: 24 }),
      ],
    }),
  );

  sections.push(clauseHeading("Payment details"));
  sections.push(
    body(
      "Payment due within 7 days of the invoice date, per the Client Services Agreement §7. Overdue amounts may accrue interest under the Penalty Interest Rates Act 1983 (Vic).",
      { after: 160 },
    ),
  );
  sections.push(pendingField("ABN"));
  sections.push(pendingField("Bank"));
  sections.push(pendingField("BSB"));
  sections.push(pendingField("Account number"));
  sections.push(
    body(
      "Status: PENDING, blocking real invoice issuance until these are supplied and this section is updated (Client Documents — Finalised, §5). This document must not be sent to a client with this section incomplete.",
      { after: 0 },
    ),
  );

  return sections;
}

export function buildInvoiceDocument(data) {
  return makeDocument({
    title: "Invoice",
    subtitle: data.isSampleTemplate ? "Template" : data.venueName,
    docLabel: `Invoice ${data.invoiceNumber}`,
    sections: buildInvoiceSections(data),
  });
}
