import type { ActivationContext, ChecklistItem, FailRule, FieldDef, FormDef } from "./types";

// The static catalog of generic compliance forms (Stage 0). B2 (the temperature log) keeps its own
// catalog entry and function. Fixed regulatory content lives in code, never in owner editable data.
//
// HOW TAGS ARE CHOSEN (Stage 0 rule): "Legally required" or "Required if" is shown only where the
// researcher confirmed it from a primary source (tagVerified). Everything else is shown as
// "Recommended record". Retention and frequency are never called a legal minimum. The T0 research
// (3 Oct 2026) could not read several primary PDFs, so most forms are recommended records. Where a
// confirmed legal limit sits INSIDE a form (a temperature, a cooling time) it is carried in ruleTag.
//
// Checklists and cleaning lists are Larder defaults (defaultList), to be reviewed by the venue.
// No copy here uses a hyphen or dash. Ranges are written with "to", negative temperatures use the
// minus sign (U+2212).

const MINUS = "−";
const BOTH = ["BOH", "FOH"] as const;

const food = (c: ActivationContext) => c.foodService !== "no_food_service";
const fullKitchen = (c: ActivationContext) => c.foodService === "full_kitchen" || c.foodService === null;
const licensedBar = (c: ActivationContext) => ["general", "on_premises", "late_night"].includes(c.licenceType ?? "");

const item = (key: string, label: string): ChecklistItem => ({ key, label });

function checklist(key: string, label: string, items: ChecklistItem[], extra?: Partial<Extract<FieldDef, { type: "checklist" }>>): FieldDef {
  return { type: "checklist", key, label, items, ...extra };
}

const anyFail = (field: string, label = "One or more checks failed"): FailRule => ({ field, op: "any_fail", label });

export const FORMS: FormDef[] = [
  // ---------------------------------------------------------------- every shift
  {
    id: "B10",
    title: "Kitchen opening checklist",
    summary: "Check the kitchen is ready and safe before food is prepared.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "shift",
    cadenceNote: "Once at the start of each trading day.",
    dueAfterHour: 11,
    estMinutes: 4,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No law names an opening checklist, but it helps you show your cleaning and temperature controls work.",
    defaultList: true,
    fields: [
      checklist("items", "Opening checks", [
        item("handwash", "Handwash basins are stocked with soap and paper towel"),
        item("sanitiser", "Sanitiser is made up at the right strength"),
        item("labels", "Food is date labelled and the oldest is at the front"),
        item("temps", "Fridges and freezers are running and temperatures are logged"),
        item("surfaces", "Benches, boards and utensils are clean"),
        item("pests", "No pest droppings or sightings"),
        item("equipment", "Equipment is switched on and working"),
        item("bins", "Bins are emptied and lined"),
      ]),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the check as failed, write what was wrong and what you did about it, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
  {
    id: "B11",
    title: "Kitchen closing checklist",
    summary: "Check the kitchen is cleaned down and food is stored safely at the end of the day.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "shift",
    cadenceNote: "Once at the end of each trading day.",
    dueAfterHour: 23,
    estMinutes: 5,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No law names a closing checklist.",
    defaultList: true,
    fields: [
      checklist("items", "Closing checks", [
        item("stored", "Food is covered, labelled and stored"),
        item("fridge", "Perishables are back in the fridge"),
        item("cooling", "Cooked food has been cooled safely or thrown out"),
        item("clean", "Benches, boards and equipment are cleaned and sanitised"),
        item("floors", "Floors are swept and mopped"),
        item("bins", "Bins are emptied"),
        item("off", "Gas and equipment are switched off"),
        item("doors", "Fridge and freezer doors are shut and temperatures are logged"),
      ]),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the check as failed, write what was wrong and what you did about it, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
  {
    id: "F1",
    title: "Front of house opening checklist",
    summary: "Check the floor, till and bar are ready before doors open.",
    group: "front",
    departments: ["FOH"],
    cadence: "shift",
    cadenceNote: "Once at the start of each trading day.",
    dueAfterHour: 11,
    estMinutes: 3,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No law names a front of house checklist.",
    defaultList: true,
    fields: [
      checklist("items", "Opening checks", [
        item("float", "Float is counted and in the till"),
        item("pos", "POS is switched on and working"),
        item("tables", "Tables, chairs and menus are set"),
        item("display", "Display fridge temperature is checked"),
        item("toilets", "Toilets are clean and stocked"),
        item("entry", "Entry and signage are clear"),
        item("floor", "Floor is clean"),
      ]),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the check as failed, write what was wrong and what you did about it, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: () => true,
    defaultOnNote: "On for every venue.",
    version: "1",
  },
  {
    id: "F2",
    title: "Front of house closing checklist",
    summary: "Check the floor, till and doors are secured at the end of the day.",
    group: "front",
    departments: ["FOH"],
    cadence: "shift",
    cadenceNote: "Once at the end of each trading day.",
    dueAfterHour: 23,
    estMinutes: 3,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No law names a front of house checklist.",
    defaultList: true,
    fields: [
      checklist("items", "Closing checks", [
        item("cash", "Till is cashed up"),
        item("wipe", "Tables and surfaces are wiped"),
        item("menus", "Menus are put away"),
        item("display", "Display fridge is closed and temperature is checked"),
        item("toilets", "Toilets are checked"),
        item("floor", "Floors are cleaned"),
        item("doors", "Doors are locked and lights are off"),
        item("bins", "Bins are taken out"),
      ]),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the check as failed, write what was wrong and what you did about it, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: () => true,
    defaultOnNote: "On for every venue.",
    version: "1",
  },

  // ---------------------------------------------------------------- daily
  {
    id: "B9",
    title: "Kitchen cleaning and sanitising",
    summary: "Tick off the cleaning and sanitising done today, area by area.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "daily",
    cadenceNote: "Once a day.",
    dueAfterHour: 22,
    estMinutes: 6,
    tag: "recommended",
    tagVerified: false,
    tagNote:
      "A recommended record. The law requires food premises to be clean and, where needed, sanitised. A written schedule is one way to show it.",
    defaultList: true,
    fields: [
      checklist(
        "items",
        "Cleaning done today",
        [
          item("floors", "Floors and drains"),
          item("handwash", "Handwash basins"),
          item("sinks", "Sinks and dishwashing area"),
          item("benches", "Benches and chopping boards"),
          item("fridge", "Fridge handles and door seals"),
          item("bins", "Bins and bin area"),
        ],
        { fromStations: { prefix: "station_", stationItemLabel: (n) => `Clean and sanitise: ${n}` } },
      ),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the area as not done, write what you did instead, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food. The areas come from this venue's stations plus a short default list.",
    version: "1",
  },
  {
    id: "F8",
    title: "Front of house cleaning",
    summary: "Tick off the cleaning done today on the floor and at the bar.",
    group: "front",
    departments: ["FOH"],
    cadence: "daily",
    cadenceNote: "Once a day.",
    dueAfterHour: 22,
    estMinutes: 4,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No law names a front of house cleaning schedule.",
    defaultList: true,
    fields: [
      checklist("items", "Cleaning done today", [
        item("tables", "Dining tables and chairs"),
        item("bartop", "Bar top"),
        item("toilets", "Toilets"),
        item("touch", "High touch areas such as door handles, card machines and menus"),
        item("floors", "Floors"),
        item("windows", "Glass and windows"),
      ]),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the area as not done, write what you did instead, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: () => true,
    defaultOnNote: "On for every venue.",
    version: "1",
  },
  {
    id: "F3",
    title: "Till and cash reconciliation",
    summary: "Count the till, compare it with the POS and have a second person sign off.",
    group: "front",
    departments: ["FOH"],
    cadence: "daily",
    cadenceNote: "Once a day at close.",
    dueAfterHour: 23,
    estMinutes: 6,
    tag: "recommended",
    tagVerified: false,
    tagNote:
      "A recommended record. Businesses must keep records of cash sales, but no law names a daily till check or a two person sign off.",
    defaultList: true,
    cosign: true,
    fields: [
      { type: "money", key: "expected_cash", label: "Cash the POS says should be in the till", hint: "Float plus cash sales from the POS report." },
      { type: "money", key: "counted_cash", label: "Cash you counted" },
      { type: "money", key: "tips", label: "Tips set aside", required: false },
    ],
    fail: [
      {
        field: "counted_cash",
        op: "differs",
        other: "expected_cash",
        value: 5,
        label: "The count is out by more than $5 (Larder default, review before use)",
      },
    ],
    failBehaviour: "Write why the count is out and what you did, then save. The second person signs off with their PIN. The owner sees it flagged.",
    allowCorrection: false,
    defaultOn: () => true,
    defaultOnNote: "On for every venue.",
    version: "1",
  },
  {
    id: "BAR2",
    title: "Glass washer check",
    summary: "Check the glass washer is running at its set temperatures and is clean.",
    group: "bar",
    departments: ["FOH"],
    cadence: "daily",
    cadenceNote: "Once a day.",
    dueAfterHour: 22,
    estMinutes: 2,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Sanitising can be done by heat or by chemical. Follow the machine's own specification.",
    defaultList: true,
    fields: [
      { type: "number", key: "wash_temp_c", label: "Wash temperature", unit: "°C", min: 0, max: 120 },
      { type: "number", key: "rinse_temp_c", label: "Rinse temperature", unit: "°C", min: 0, max: 120 },
      { type: "passfail", key: "temps_ok", label: "Temperatures match the machine's specification", passLabel: "Matches", failLabel: "Does not match" },
      { type: "passfail", key: "chemicals_ok", label: "Detergent and rinse aid are topped up", passLabel: "Topped up", failLabel: "Needs topping up" },
      { type: "passfail", key: "filter_ok", label: "Filter is clean", passLabel: "Clean", failLabel: "Needs cleaning" },
    ],
    fail: [
      { field: "temps_ok", op: "eq", value: "fail", label: "Temperatures do not match the specification" },
      { field: "chemicals_ok", op: "eq", value: "fail", label: "Detergent or rinse aid needs topping up" },
      { field: "filter_ok", op: "eq", value: "fail", label: "Filter needs cleaning" },
    ],
    failBehaviour: "Write what you did, for example cleaned the filter or called the technician, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: licensedBar,
    defaultOnNote: "On for venues with a bar licence.",
    version: "1",
  },
  {
    id: "BAR3",
    title: "Cellar and keg check",
    summary: "Check gas cylinders, couplers and the cellar are safe.",
    group: "bar",
    departments: ["FOH"],
    cadence: "daily",
    cadenceNote: "Once a day.",
    dueAfterHour: 22,
    estMinutes: 3,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. General workplace safety duties apply to gas cylinders, but no rule for a cellar log was confirmed.",
    defaultList: true,
    fields: [
      checklist("items", "Cellar checks", [
        item("cylinders", "Gas cylinders are upright and chained"),
        item("couplers", "Couplers and hoses are in good condition"),
        item("kegs", "Kegs are in date and the oldest are used first"),
        item("floor", "Floor is clear and dry"),
        item("seals", "Cool room door seals are sound"),
      ]),
      { type: "number", key: "cool_room_temp_c", label: "Cool room temperature", unit: "°C", min: -10, max: 40, required: false, hint: "Recorded only. Beer cellars usually run warmer than a food fridge." },
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the check as failed, write what you did about it, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: licensedBar,
    defaultOnNote: "On for venues with a bar licence.",
    version: "1",
  },
  {
    id: "CAFE1",
    title: "Display cabinet temperatures",
    summary: "Record the temperature of a food display cabinet.",
    group: "cafe",
    departments: ["FOH", "BOH"],
    cadence: "daily",
    cadenceNote: "Once a day, more often if you wish. One record per cabinet.",
    dueAfterHour: 12,
    estMinutes: 1,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. The temperature rule itself is a legal limit (see below).",
    ruleTag: { tag: "legal", text: "Food that can grow bacteria must be kept at 5°C or colder, or at 60°C or hotter." },
    subjectField: "cabinet",
    fields: [
      { type: "text", key: "cabinet", label: "Which cabinet", maxLength: 60 },
      {
        type: "choice",
        key: "mode",
        label: "What it holds",
        options: [
          { value: "cold", label: "Cold food" },
          { value: "hot", label: "Hot food" },
        ],
      },
      { type: "number", key: "temp_c", label: "Temperature", unit: "°C", min: -30, max: 120, allowNegative: true },
    ],
    fail: [
      { field: "temp_c", op: "gt", value: 5, when: { field: "mode", value: "cold" }, label: "Cold food is warmer than 5°C" },
      { field: "temp_c", op: "lt", value: 60, when: { field: "mode", value: "hot" }, label: "Hot food is cooler than 60°C" },
    ],
    failBehaviour: "Write what you did, for example moved or threw out the food, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: () => false,
    defaultOnNote: "Off until the owner switches it on. The wizard does not yet record whether a venue runs a cafe.",
    version: "1",
  },
  {
    id: "CAFE2",
    title: "Coffee machine cleaning",
    summary: "Tick off the daily coffee machine clean.",
    group: "cafe",
    departments: ["FOH", "BOH"],
    cadence: "daily",
    cadenceNote: "Once a day at close.",
    dueAfterHour: 16,
    estMinutes: 3,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Only the general duty to keep equipment clean applies.",
    defaultList: true,
    fields: [
      checklist("items", "Daily clean", [
        item("backflush", "Group heads backflushed with cleaner"),
        item("wand", "Steam wand purged and wiped"),
        item("portafilters", "Portafilters and baskets cleaned"),
        item("tray", "Drip tray emptied and rinsed"),
        item("wipe", "Machine and grinder wiped down"),
      ]),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the check as failed, write what you did about it, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: () => false,
    defaultOnNote: "Off until the owner switches it on.",
    version: "1",
  },

  // ---------------------------------------------------------------- weekly, monthly, yearly
  {
    id: "BAR1",
    title: "Beer line cleaning",
    summary: "Record each beer line clean: which lines, the chemical and the rinse check.",
    group: "bar",
    departments: ["FOH"],
    cadence: "weekly",
    cadenceNote: "Weekly is the common industry practice. Some venues clean every two weeks.",
    estMinutes: 3,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No rule fixing how often beer lines must be cleaned was found.",
    defaultList: true,
    fields: [
      { type: "text", key: "lines", label: "Which lines were cleaned", maxLength: 120 },
      { type: "text", key: "chemical", label: "Cleaning chemical used", maxLength: 80 },
      { type: "number", key: "contact_minutes", label: "Contact time", unit: "minutes", min: 1, max: 240 },
      { type: "passfail", key: "rinse_ok", label: "Lines rinsed clear and tasted fine", passLabel: "Rinsed clear", failLabel: "Not clear" },
    ],
    fail: [{ field: "rinse_ok", op: "eq", value: "fail", label: "Lines did not rinse clear" }],
    failBehaviour: "Write what you did, for example rinsed again, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: licensedBar,
    defaultOnNote: "On for venues with a bar licence.",
    version: "1",
  },
  {
    id: "CAFE3",
    title: "Coffee machine descale",
    summary: "Record the weekly descale of the coffee machine.",
    group: "cafe",
    departments: ["FOH", "BOH"],
    cadence: "weekly",
    cadenceNote: "Once a week.",
    estMinutes: 10,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Follow the machine maker's guidance for how often.",
    fields: [
      { type: "passfail", key: "descaled", label: "Machine descaled and rinsed", passLabel: "Done", failLabel: "Not done" },
      { type: "text", key: "product", label: "Descaler used", maxLength: 80, required: false },
    ],
    fail: [{ field: "descaled", op: "eq", value: "fail", label: "Descale not completed" }],
    failBehaviour: "Write why it was not done, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: () => false,
    defaultOnNote: "Off until the owner switches it on.",
    version: "1",
  },
  {
    id: "F6",
    title: "First aid kit check",
    summary: "Check the first aid kit is complete, in date and in its place.",
    group: "venue",
    departments: ["FOH", "BOH"],
    cadence: "monthly",
    cadenceNote: "Once a month.",
    estMinutes: 4,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Workplaces must provide first aid facilities, but no check frequency was confirmed.",
    defaultList: true,
    fields: [
      checklist("items", "Kit checks", [
        item("plasters", "Plasters and dressings are in date"),
        item("bandages", "Bandages and tape are stocked"),
        item("gloves", "Gloves are stocked"),
        item("antiseptic", "Antiseptic wipes are in date"),
        item("eyewash", "Eyewash is in date"),
        item("tools", "Scissors and tweezers are present"),
        item("place", "Kit is sealed and in its marked place"),
        item("restocked", "Anything used has been replaced"),
      ]),
    ],
    fail: [anyFail("items")],
    failBehaviour: "Mark the item as failed, write what you did, for example reordered supplies, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: () => true,
    defaultOnNote: "On for every venue.",
    version: "1",
  },
  {
    id: "B4",
    title: "Probe thermometer check",
    summary: "Check each probe thermometer reads true in iced water and in boiling water.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "annual",
    cadenceNote: "Once a year is a common Larder default. Check more often if a probe is dropped.",
    estMinutes: 5,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. The accuracy of the thermometer is a legal duty (see below), but no check frequency is stated in law.",
    ruleTag: { tag: "legal", text: "A thermometer used to check food temperatures must be accurate to within 1°C." },
    subjectField: "thermometer",
    fields: [
      { type: "text", key: "thermometer", label: "Which thermometer", maxLength: 60, hint: "For example Probe 1 or the red probe." },
      { type: "number", key: "ice_c", label: "Reading in iced water", unit: "°C", min: -10, max: 10, allowNegative: true, hint: `Should read between ${MINUS}1°C and 1°C.` },
      { type: "number", key: "boil_c", label: "Reading in boiling water", unit: "°C", min: 90, max: 105, hint: "Should read between 99°C and 101°C." },
    ],
    fail: [
      { field: "ice_c", op: "outside", min: -1, max: 1, label: `Iced water reading is outside ${MINUS}1°C to 1°C` },
      { field: "boil_c", op: "outside", min: 99, max: 101, label: "Boiling water reading is outside 99°C to 101°C" },
    ],
    failBehaviour: "Write that the probe was replaced or adjusted, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: fullKitchen,
    defaultOnNote: "On for venues with a full kitchen.",
    version: "1",
  },

  // ---------------------------------------------------------------- when it happens
  {
    id: "B3",
    title: "Goods receiving check",
    summary: "Check a delivery on arrival: temperature, packaging, dates and whether you accept it.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each time a chilled, frozen or hot delivery arrives. Dry goods do not need a temperature.",
    estMinutes: 2,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. The temperature limits are a legal duty (see below). A written receiving record is one way to show it.",
    ruleTag: { tag: "legal", text: "Food that can grow bacteria must be received at 5°C or colder, or at 60°C or hotter." },
    fields: [
      { type: "text", key: "supplier", label: "Supplier", maxLength: 80 },
      { type: "text", key: "product", label: "Product", maxLength: 80 },
      {
        type: "choice",
        key: "temp_type",
        label: "Delivered as",
        options: [
          { value: "chilled", label: "Chilled" },
          { value: "frozen", label: "Frozen" },
          { value: "hot", label: "Hot" },
        ],
      },
      { type: "number", key: "temp_c", label: "Temperature", unit: "°C", min: -40, max: 120, allowNegative: true },
      { type: "passfail", key: "packaging", label: "Packaging is clean and undamaged", passLabel: "Good", failLabel: "Damaged" },
      { type: "passfail", key: "dates", label: "Use by dates are in date", passLabel: "In date", failLabel: "Out of date" },
      {
        type: "choice",
        key: "decision",
        label: "Decision",
        options: [
          { value: "accepted", label: "Accepted" },
          { value: "rejected", label: "Rejected" },
        ],
      },
    ],
    fail: [
      { field: "temp_c", op: "gt", value: 5, when: { field: "temp_type", value: "chilled" }, label: "Chilled delivery is warmer than 5°C" },
      { field: "temp_c", op: "gt", value: -15, when: { field: "temp_type", value: "frozen" }, label: `Frozen delivery is warmer than ${MINUS}15°C` },
      { field: "temp_c", op: "lt", value: 60, when: { field: "temp_type", value: "hot" }, label: "Hot delivery is cooler than 60°C" },
      { field: "packaging", op: "eq", value: "fail", label: "Packaging is damaged" },
      { field: "dates", op: "eq", value: "fail", label: "Use by date has passed" },
      { field: "decision", op: "eq", value: "rejected", label: "Delivery rejected" },
    ],
    failBehaviour: "Write what you did, for example rejected the delivery and told the supplier, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: fullKitchen,
    defaultOnNote: "On for venues with a full kitchen.",
    version: "1",
  },
  {
    id: "B5",
    title: "Cooking core temperature",
    summary: "Record the core temperature of cooked food.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "For chicken, mince, burgers and other foods you cook to a core temperature.",
    estMinutes: 1,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. 75°C is common guidance, not a figure in the Food Standards Code.",
    defaultList: true,
    fields: [
      { type: "text", key: "item", label: "What you cooked", maxLength: 80 },
      { type: "number", key: "core_temp_c", label: "Core temperature", unit: "°C", min: 0, max: 150 },
    ],
    fail: [{ field: "core_temp_c", op: "lt", value: 75, label: "Below 75°C (Larder default, review before use)" }],
    failBehaviour: "Write what you did, for example cooked it longer, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: fullKitchen,
    defaultOnNote: "On for venues with a full kitchen.",
    version: "1",
  },
  {
    id: "B7",
    title: "Reheating log",
    summary: "Record the core temperature of food you reheat.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each time you reheat cooked and cooled food that will be held hot.",
    estMinutes: 1,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Reheating to a safe temperature is a legal duty in the case below.",
    ruleTag: {
      tag: "legal",
      text: "Cooked and cooled food that will be held hot must be reheated quickly to 60°C or hotter. Larder's default check is higher, at 75°C.",
    },
    defaultList: true,
    fields: [
      { type: "text", key: "item", label: "What you reheated", maxLength: 80 },
      { type: "number", key: "core_temp_c", label: "Core temperature", unit: "°C", min: 0, max: 150 },
    ],
    fail: [{ field: "core_temp_c", op: "lt", value: 75, label: "Below 75°C (Larder default, review before use)" }],
    failBehaviour: "Write what you did, for example reheated it again or threw it out, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: fullKitchen,
    defaultOnNote: "On for venues with a full kitchen.",
    version: "1",
  },
  {
    id: "B8",
    title: "2 hour and 4 hour rule log",
    summary: "Record food left out of temperature control and what happened to it.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each time food sits out of the fridge or hot hold.",
    estMinutes: 1,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. The 2 hour and 4 hour rule is published food safety guidance, not a rule in the Food Standards Code.",
    fields: [
      { type: "text", key: "item", label: "What was out", maxLength: 80 },
      { type: "time", key: "time_out", label: "Time it came out" },
      {
        type: "choice",
        key: "outcome",
        label: "What happened to it",
        options: [
          { value: "used_within_2h", label: "Used or sold within 2 hours" },
          { value: "used_2_to_4h", label: "Used or sold between 2 and 4 hours" },
          { value: "refrigerated", label: "Put back in the fridge within 2 hours" },
          { value: "discarded", label: "Thrown out" },
        ],
      },
    ],
    fail: [{ field: "outcome", op: "eq", value: "discarded", label: "Food was thrown out" }],
    failBehaviour: "Write what was thrown out and why, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: fullKitchen,
    defaultOnNote: "On for venues with a full kitchen.",
    version: "1",
  },
  {
    id: "B6",
    title: "Two stage cooling log",
    summary: "Cool cooked food safely: start it, then check it at 2 hours and again at 6 hours.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each batch you cool. Three steps: start, 2 hour check, 6 hour check.",
    estMinutes: 2,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. The cooling times are a legal duty (see below). A written log is one way to show it.",
    ruleTag: {
      tag: "legal",
      text: "Cooked food must cool from 60°C to 21°C within 2 hours, then from 21°C to 5°C within a further 4 hours.",
    },
    fields: [],
    fail: [],
    stages: [
      {
        key: "start",
        label: "Start cooling",
        chain: "new",
        departments: ["BOH"],
        blurb: "Log the batch when it comes off the heat. You will check it again at 2 hours and 6 hours.",
        fields: [
          { type: "text", key: "item", label: "What you are cooling", maxLength: 80 },
          { type: "number", key: "start_temp_c", label: "Starting temperature", unit: "°C", min: 0, max: 150 },
        ],
        fail: [],
      },
      {
        key: "two_hour",
        label: "2 hour check",
        chain: "existing",
        requires: "start",
        elapsedMaxMin: 120,
        elapsedLabel: "Checked after the 2 hour limit",
        departments: ["BOH"],
        blurb: "Within 2 hours of the start the food must be at 21°C or colder.",
        fields: [{ type: "number", key: "temp_c", label: "Temperature now", unit: "°C", min: -30, max: 150, allowNegative: true }],
        fail: [{ field: "temp_c", op: "gt", value: 21, label: "Warmer than 21°C" }],
      },
      {
        key: "six_hour",
        label: "6 hour check",
        chain: "existing",
        requires: "start",
        requiresPrior: ["two_hour"],
        elapsedMaxMin: 360,
        elapsedLabel: "Checked after the 6 hour limit",
        departments: ["BOH"],
        blurb: "Within 6 hours of the start the food must be at 5°C or colder.",
        fields: [{ type: "number", key: "temp_c", label: "Temperature now", unit: "°C", min: -30, max: 150, allowNegative: true }],
        fail: [{ field: "temp_c", op: "gt", value: 5, label: "Warmer than 5°C" }],
      },
    ],
    failBehaviour: "If a check is late or too warm, write what you did, for example threw the batch out, then save. The owner sees it flagged.",
    allowCorrection: false,
    defaultOn: fullKitchen,
    defaultOnNote: "On for venues with a full kitchen.",
    version: "1",
  },
  {
    id: "B12",
    title: "Pest control log",
    summary: "Record pest sightings, trap checks and contractor visits.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each sighting, trap check or contractor visit.",
    estMinutes: 2,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. The law requires you to keep pests out, but names no pest log. Keep contractor reports as well.",
    fields: [
      {
        type: "choice",
        key: "kind",
        label: "What happened",
        options: [
          { value: "sighting", label: "Pest sighting" },
          { value: "trap_check", label: "Trap check, nothing found" },
          { value: "contractor_visit", label: "Contractor visit" },
        ],
      },
      { type: "text", key: "location", label: "Where", maxLength: 80 },
      { type: "text", key: "detail", label: "Detail", maxLength: 200, required: false },
    ],
    fail: [{ field: "kind", op: "eq", value: "sighting", label: "Pest sighting" }],
    failBehaviour: "Write what you did about the sighting, then save. The owner sees it flagged.",
    allowCorrection: true,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
  {
    id: "B13",
    title: "Grease trap and waste log",
    summary: "Record each grease trap pump out and keep the docket reference.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each pump out. How often is set by your trade waste agreement.",
    estMinutes: 2,
    event: true,
    tag: "required_if",
    tagVerified: true,
    tagNote:
      "Required if you have a Trade Waste Agreement with your water authority. Yarra Valley Water asks you to keep pump out receipts. Other water authorities were not checked.",
    fields: [
      { type: "text", key: "contractor", label: "Contractor", maxLength: 80 },
      { type: "number", key: "volume_litres", label: "Volume removed", unit: "litres", min: 0, max: 100000 },
      { type: "text", key: "docket", label: "Docket reference", maxLength: 60, required: false },
    ],
    fail: [],
    failBehaviour: "This form has no fail state. Keep the paper docket with the venue's food safety documents.",
    allowCorrection: true,
    defaultOn: (c) => c.tradeWaste === "yes",
    defaultOnNote: "On when the venue has a Trade Waste Agreement.",
    version: "1",
  },
  {
    id: "B17",
    title: "Corrective action log",
    summary: "Record a food safety problem, what food it affected and what you did.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each time something goes wrong that is not covered by another form.",
    estMinutes: 3,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Your Food Safety Program may require records of the action you take.",
    fields: [
      { type: "text", key: "issue", label: "What went wrong", maxLength: 300, multiline: true },
      { type: "text", key: "food_affected", label: "Food affected", maxLength: 200, required: false },
      { type: "text", key: "action_taken", label: "What you did", maxLength: 300, multiline: true },
      { type: "text", key: "verified_by", label: "Checked by", maxLength: 60, required: false },
    ],
    fail: [],
    failBehaviour: "This form is the corrective action record. It has no pass or fail.",
    allowCorrection: true,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
  {
    id: "B18",
    title: "Equipment repair log",
    summary: "Record equipment faults, who fixed them and when.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Each fault or repair.",
    estMinutes: 2,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No law names an equipment repair log.",
    fields: [
      { type: "text", key: "equipment", label: "Equipment", maxLength: 80 },
      { type: "text", key: "fault", label: "Fault", maxLength: 200 },
      { type: "text", key: "technician", label: "Technician", maxLength: 80, required: false },
      {
        type: "choice",
        key: "status",
        label: "Status",
        options: [
          { value: "reported", label: "Reported" },
          { value: "repaired", label: "Repaired" },
          { value: "replaced", label: "Replaced" },
        ],
      },
    ],
    fail: [],
    failBehaviour: "This form has no pass or fail.",
    allowCorrection: true,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
  {
    id: "F7",
    title: "Allergen request ticket",
    summary: "Front of house logs an allergen request and the kitchen confirms it can be made safely.",
    group: "front",
    departments: ["FOH", "BOH"],
    visibleTo: ["FOH", "BOH"],
    cadence: "event",
    cadenceNote: "Each guest allergen or dietary request. Two steps: front of house logs it, the kitchen confirms.",
    estMinutes: 1,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Businesses must give allergen information on request, but no ticket record is named in law.",
    fields: [],
    fail: [],
    stages: [
      {
        key: "ticket",
        label: "Log the request",
        chain: "new",
        departments: ["FOH"],
        blurb: "Log what the guest asked for. Do not enter the guest's name.",
        fields: [
          { type: "text", key: "reference", label: "Table or order number", maxLength: 30 },
          { type: "text", key: "dish", label: "Dish", maxLength: 80 },
          { type: "text", key: "allergens", label: "Allergens to avoid", maxLength: 120 },
          {
            type: "choice",
            key: "severity",
            label: "How serious",
            options: [
              { value: "preference", label: "Dietary preference" },
              { value: "intolerance", label: "Intolerance" },
              { value: "allergy", label: "Allergy" },
              { value: "anaphylaxis", label: "Risk of anaphylaxis" },
            ],
          },
        ],
        fail: [],
      },
      {
        key: "confirm",
        label: "Kitchen confirms",
        chain: "existing",
        requires: "ticket",
        departments: ["BOH"],
        blurb: "Check the dish against the request and confirm it can be made safely.",
        fields: [{ type: "passfail", key: "can_make", label: "The kitchen can make this dish safely", passLabel: "Can make it safely", failLabel: "Cannot make it safely" }],
        fail: [{ field: "can_make", op: "eq", value: "fail", label: "The kitchen cannot make it safely" }],
      },
    ],
    failBehaviour: "If the kitchen cannot make it safely, write what the guest was told, then save. The owner sees it flagged.",
    allowCorrection: false,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
  {
    id: "F10",
    title: "Refusal of service log",
    summary: "Record when service is refused or a guest is asked to leave. Do not enter patron names.",
    group: "bar",
    departments: ["FOH"],
    cadence: "event",
    cadenceNote: "Each refusal.",
    estMinutes: 2,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No Victorian rule for a refusal register was found. It is good practice to show responsible service.",
    fields: [
      {
        type: "choice",
        key: "outcome",
        label: "What happened",
        options: [
          { value: "refused", label: "Service refused" },
          { value: "asked_to_leave", label: "Asked to leave" },
          { value: "monitored", label: "Water offered and monitored" },
        ],
      },
      { type: "text", key: "signs", label: "Signs you saw", maxLength: 300, multiline: true, hint: "Describe behaviour. Do not enter names." },
      { type: "text", key: "action", label: "What you did", maxLength: 300, multiline: true },
    ],
    fail: [],
    failBehaviour: "This form has no pass or fail. Never enter patron names.",
    allowCorrection: true,
    defaultOn: licensedBar,
    defaultOnNote: "On for venues with a bar licence.",
    version: "1",
  },
  {
    id: "F13",
    title: "Lost property log",
    summary: "Record items found and what happened to them.",
    group: "front",
    departments: ["FOH"],
    cadence: "event",
    cadenceNote: "Each item found.",
    estMinutes: 1,
    event: true,
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. No law names a lost property log.",
    fields: [
      { type: "text", key: "item", label: "Item", maxLength: 80 },
      { type: "text", key: "found_where", label: "Found where", maxLength: 80 },
      {
        type: "choice",
        key: "status",
        label: "Status",
        options: [
          { value: "held", label: "Held at the venue" },
          { value: "returned", label: "Returned to the owner" },
          { value: "police", label: "Handed to police" },
          { value: "discarded", label: "Discarded" },
        ],
      },
    ],
    fail: [],
    failBehaviour: "This form has no pass or fail.",
    allowCorrection: true,
    defaultOn: () => true,
    defaultOnNote: "On for every venue.",
    version: "1",
  },

  // ---------------------------------------------------------------- registers
  {
    id: "B1",
    title: "Supplier register",
    summary: "Keep a list of your suppliers with their contact details.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Add a supplier when you start buying from them. Retire them when you stop.",
    estMinutes: 2,
    kind: "register",
    tag: "recommended",
    tagVerified: false,
    tagNote: "A recommended record. Food must be traceable to its source. A supplier list helps you show that.",
    subjectField: "name",
    fields: [
      { type: "text", key: "name", label: "Supplier name", maxLength: 80 },
      { type: "text", key: "address", label: "Address", maxLength: 160, required: false },
      { type: "text", key: "phone", label: "Phone", maxLength: 30, required: false },
      {
        type: "choice",
        key: "status",
        label: "Status",
        options: [
          { value: "active", label: "Active" },
          { value: "retired", label: "No longer used" },
        ],
      },
    ],
    fail: [],
    failBehaviour: "A register has no pass or fail. Saving a name again updates that supplier.",
    allowCorrection: false,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
  {
    id: "B20",
    title: "Chemical register",
    summary: "Keep a list of cleaning chemicals, how they are used and whether the safety data sheet is on file.",
    group: "kitchen",
    departments: ["BOH"],
    cadence: "event",
    cadenceNote: "Add a chemical when you start using it. Retire it when you stop.",
    estMinutes: 2,
    kind: "register",
    tag: "recommended",
    tagVerified: false,
    tagNote:
      "A recommended record. Whether a register and safety data sheets are mandatory depends on the products and your workplace safety rules. Check with WorkSafe.",
    subjectField: "product",
    fields: [
      { type: "text", key: "product", label: "Product", maxLength: 80 },
      { type: "text", key: "use", label: "What it is used for", maxLength: 120 },
      { type: "text", key: "dilution", label: "Dilution", maxLength: 60, required: false },
      {
        type: "choice",
        key: "sds",
        label: "Safety data sheet on file",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        type: "choice",
        key: "status",
        label: "Status",
        options: [
          { value: "active", label: "Active" },
          { value: "retired", label: "No longer used" },
        ],
      },
    ],
    fail: [],
    failBehaviour: "A register has no pass or fail. Saving a product again updates that entry.",
    allowCorrection: false,
    defaultOn: food,
    defaultOnNote: "On for venues that serve food.",
    version: "1",
  },
];

export const FORM_BY_ID: Record<string, FormDef> = Object.fromEntries(FORMS.map((f) => [f.id, f]));

export function getGenericForm(id: string): FormDef | null {
  return FORM_BY_ID[id] ?? null;
}

/** Forms that only link to existing features (no new records). */
export const LINKED_FEATURES = [
  { id: "B14", title: "Food Safety Supervisor record", note: "Tracked as a certificate type for each staff member.", kind: "certs" as const },
  { id: "F9", title: "RSA certificate register", note: "Tracked as a certificate type for each staff member.", kind: "certs" as const },
  { id: "B19", title: "Allergen matrix", note: "Built from the allergens on each menu item.", kind: "menu" as const },
  { id: "B15", title: "Food handler training register", note: "Read only list of completed training modules.", kind: "training" as const },
];

/** Forms deliberately not built in Stage 0, with the reason (shown in the report). */
export const HELD_FORMS = [
  { id: "B16", title: "Staff illness and exclusion log", reason: "Holds health information about named staff. Needs a privacy decision first." },
  { id: "F4", title: "Incident and accident report", reason: "Notifiable incidents go to WorkSafe and need a reviewed legal flow." },
  { id: "F5", title: "Register of Injuries", reason: "A legal register with its own retention rules. Needs a reviewed legal flow." },
  { id: "F6T", title: "First aid treatment log", reason: "Holds health information about named people. Needs a privacy decision first." },
  { id: "F12", title: "Barring order record", reason: "Holds names and dates of birth and must be destroyed on a legal schedule. Needs a reviewed legal flow." },
  { id: "F11", title: "Liquor incident register", reason: "Required only by licence condition or accord. Needs the venue's actual condition." },
  { id: "B21", title: "Food Safety Program activity records", reason: "Per activity records from the FoodSmart numbered sheets, which could not be read." },
  { id: "RES", title: "Residents' register", reason: "Needs a legal review of what must be kept. Out of Stage 0 scope." },
  { id: "RSG", title: "Gaming and responsible service of gaming", reason: "Gaming compliance is out of scope by decision (29 Sep)." },
];

export function formsByGroup() {
  return FORMS.reduce<Record<string, FormDef[]>>((acc, f) => {
    (acc[f.group] ||= []).push(f);
    return acc;
  }, {});
}
